#!/bin/bash
export SCRIPTSDIR="$HOME/Dropbox (Personal)/Permanent/Computers/Tools/Mac"
source ~/.bashrc_base

#
# PATH
#

# node
PATH=$HOME/.node_modules/bin:$HOME/scripts:$PATH:
# mysql
PATH="$PATH:/opt/pkgconfig/bin:/usr/local/mysql/bin"
# mongodb
#PATH="$PATH:/Applications/mongodb/bin"

# Homebrew
# ctags for vim
PATH="/usr/local/Cellar/ctags/5.8_1/bin:$PATH"
# python3
PATH="/usr/local/Cellar/python3/3.4.3/bin:$PATH"
export PATH

#
# Exaptive language
#
# - Used by the Exaptive domains to find the language directory.
EXAPTIVE_LANGUAGE_PATH="$HOME/Projects/stack/exaptive/language"
export EXAPTIVE_LANGUAGE_PATH


#
# Python
#
PYTHONPATH="$PYTHONPATH:$HOME/Sites/exaptive/exaptive-core/server/rdo/python/api"
export PYTHONPATH
alias python3="python3.4"


#
# Node.js
#
# NODE_PATH
NODE_PATH='/usr/local/lib/jsctags:${NODE_PATH}'
export NODE_PATH

export GATK_PATH="$HOME/Documents/Projects/Seracare/GATK/GenomeAnalysisTK.jar"
