#!/bin/bash
export SCRIPTSDIR="$HOME/Dropbox (Personal)/Permanent/Computers/Tools/Mac"
source ~/.bashrc


#
# PATH
#
addToPathIfExists() {
	local path="$1"
	if [[ -d $path ]];
	then
		PATH="$path:$PATH"

	fi
}

addToPathIfExists "$HOME/scripts"
# npm package commands
addToPathIfExists "$HOME/.node_modules/bin"
# mysql
addToPathIfExists "/opt/pkgconfig/bin:/usr/local/mysql/bin"
# Latex
addToPathIfExists "/Library/Tex/texbin"


#
# Homebrew
#
# ctags for vim
PATH="/usr/local/Cellar/ctags/5.8_1/bin:$PATH"
# python3
#PATH="/usr/local/Cellar/python3/3.4.3/bin:$PATH"
export PATH


#
# Python
#
PYTHONPATH="$PYTHONPATH:$HOME/Sites/exaptive/exaptive-core/server/rdo/python/api"
export PYTHONPATH


#
# Node.js
#
# NODE_PATH
NODE_PATH='/usr/local/lib/jsctags:${NODE_PATH}'
export NODE_PATH


#
# Other Variables
#
# EXAPTIVE_LANGUAGE_PATH: Used by the Exaptive domains to find the language directory.
export EXAPTIVE_LANGUAGE_PATH="$HOME/Projects/exaptive_stack/exaptive/node_modules"

# GATK_PATH:
export GATK_PATH="$HOME/Documents/Projects/Seracare/GATK/GenomeAnalysisTK.jar"

# iTune
export ITUNES_MUSIC="$HOME/Music/iTunes/iTunes Media/Music"

# SSL
export SSLKEYLOGFILE=$HOME/.sslkeylog

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"
