#!/bin/bash
export MY_BIN="$HOME/.bin_yui"
export TOOLS_YUI="$HOME/.tools_yui"
export BASHRC_YUI="${TOOLS_YUI}/dotfiles/bashrc"
export BASHRCBASE_PATH="$BASHRC_YUI/bashrc_base"

#
# Check if MAC
# 
export IS_MAC=$([[ -z $(uname | grep Darwin) ]]; echo $?)


# Auto completion with git
if [[ -f "${MY_BIN}/git-completion.bash" ]]
then
	source "${MY_BIN}/git-completion.bash"
fi

#
# PS1
#
# See PROMPTING in man bash
#
# \s = Shell
# \h = hostname
# \H = Full hostname
# \u = Current user
# \w = Current directory from the user's home directory
# \W = Current directory
BLACK="\[$(tput setaf 0)\]"
RED="\[$(tput setaf 1)\]"
GREEN="\[$(tput setaf 2)\]"
YELLOW="\[$(tput setaf 3)\]"
BLUE="\[$(tput setaf 4)\]"
PINK="\[$(tput setaf 5)\]"
LIGHTBLUE="\[$(tput setaf 6)\]"
WHITE="\[$(tput setaf 7)\]"
DEFAULT="\[$(tput setaf 9)\]"
RESET="\[$(tput sgr0)\]"
export PS1="${WHITE}\u${RESET}@${WHITE}\h${RESET}:${BLUE}\W${RESET} [j=${RED}\j${RESET}] >> "


#
# Functions
#

PrintSystemInfo() {
	echo "Bash:$SHELL $BASH_VERSION"
	echo "Date:$(date)"
	echo "Kernel:$(uname -a)"
	echo "User:$(whoami)"
	echo "Host:$(hostname)"
}
# Bug: printing here caused problems when uploading with scp.
#PrintSystemInfo


#
# Aliases
#
alias pu="pushd"
alias po="popd"
alias ll="ls -alF"
alias la="ls -A"
alias rm="rm -i"
alias cp="cp -i"
alias mv="mv -i"
alias less="less -N"

alias doublequote="sed -e 's/\(.*\)/\"\1\"/'"
alias singlequote="sed -e \"s/\(.*\)/'\1'/\""
alias timecmd="/usr/bin/time /bin/bash -c"

# To enable <C-S> to work in vim.
alias vim="stty stop '' -ixoff; vim"

# Include local node_modules in path
# https://stackoverflow.com/questions/9679932/how-to-use-package-installed-locally-in-node-modules
alias npm-exec='PATH=$(npm bin):$PATH'


#
# Path
#
# Take backup so that if this bashrc is reloaded, we don't duplicate paths.
if [[ ! $PATH_BAK ]]; then PATH_BAK=$PATH; fi
PATH=$PATH_BAK

PATH=/usr/sbin:$PATH
PATH=/usr/local/bin:/usr/sbin:$PATH
PATH="$MY_BIN:$PATH"
PATH=$HOME/.node_modules/bin:$PATH:
export PATH_BAK
export PATH


#
# Custom bashrc
# Do this last. Otherwise, may get overwritten by default.
#
if [[ $IS_MAC == 1 ]]
then
	source "$BASHRC_YUI/bashrc_mac"
fi
