#!/bin/bash
main() {
	echo "Loading ${BASH_SOURCE[0]}"
	setupAlias
	setupEnv
	setupCustomVariables
}

setupAlias() {
	#
	# Alias
	#
	alias ytop="top -r -S -stats pid,command,cpu,mem,user,time,state,rprvt,vsize,vprvt,kprvt,kshrd,purg"
	alias ls="ls -FG"
	alias ll="ls -alFG" 	# G for color
	alias la="ls -AG"
	PSCOLUMNS="pid,ppid,user,%cpu,%mem,rss,vsz,comm"
	alias ypscpu="CommandWithLess ps -Ar -o $PSCOLUMNS"
	alias ypsmem="CommandWithLess ps -Am -o $PSCOLUMNS"
	alias ypsid="ps -Ao pid,ppid,pgid,rgid,user,uid,tt,command"
	alias yshutdown="sudo /sbin/shutdown -h now"

	# Sar
	let SARINTERVAL=10
	let SARCOUNT="(60 * 60 * 24) / SARINTERVAL"		# A day
	DoSar() {
		TYPE=$1
		INTERVAL=$2
		COUNT=$3
		if [[ ! $INTERVAL ]]; then INTERVAL=$SARINTERVAL; fi
		if [[ ! $COUNT ]]
		then 
			let COUNT="$SARCOUNT"
		fi
		sar "$TYPE $INTERVAL $COUNT"
	}
	alias saru="DoSar -u"
	alias sard="DoSar -d"
	alias sarn="DoSar \"-n DEV\""
}

setupEnv() {
	#
	# Mac specific settings
	#
	#export TERM='xterm-color'
	#alias tmux="TERM=screen-256color-bce tmux"
	#alias tmux="tmux -2"

	# Allow forward search with Ctrl-S
	stty stop undef

	setupPath
}

setupPath() {
	PATH=/usr/lib:$PATH
	PATH=$HOME/local/bin:$PATH
	export PATH
}

setupCustomVariables() {
	# Nothing yet
	: 
}

main
