#!/bin/bash

main() {
	echo "Loading ${BASH_SOURCE[0]}"
	setupAlias
	setupEnv
	setupCustomVariables
	setupTools
}

setupAlias() {
	#
	# Alias
	#
	alias ytop="top -r -S -stats pid,command,cpu,mem,user,time,state,rprvt,vsize,vprvt,kprvt,kshrd,purg"
	alias ls="ls -G"
	alias ll="ls -alFG" 	# G=color F=show type 
	alias la="ls -AG"
	PSCOLUMNS="pid,ppid,user,%cpu,%mem,rss,vsz,comm"
	alias ypscpu="CommandWithLess ps -Ar -o $PSCOLUMNS"
	alias ypsmem="CommandWithLess ps -Am -o $PSCOLUMNS"
	alias ypsid="ps -Ao pid,ppid,pgid,rgid,user,uid,tt,command"
	alias yshutdown="sudo /sbin/shutdown -h now"

	# Sar
	let SARINTERVAL=10
	let SARCOUNT="(60 * 60 * 24) / SARINTERVAL"		# A day
	DoSar() {
		TYPE=$1
		INTERVAL=$2
		COUNT=$3
		if [[ ! $INTERVAL ]]; then INTERVAL=$SARINTERVAL; fi
		if [[ ! $COUNT ]]
		then 
			let COUNT="$SARCOUNT"
		fi
		sar "$TYPE $INTERVAL $COUNT"
	}
	alias saru="DoSar -u"
	alias sard="DoSar -d"
	alias sarn="DoSar \"-n DEV\""
}

setupEnv() {
	#
	# Mac specific settings
	#
	#export TERM='xterm-color'
	#alias tmux="TERM=screen-256color-bce tmux"
	#alias tmux="tmux -2"

	# Allow forward search with Ctrl-S
	stty stop undef

	setupPath
}

setupPath() {
	PATH=/usr/lib:$PATH
	PATH=$HOME/local/bin:$PATH
	PATH="$TOOLS_YUI/scripts:$PATH"
	PATH="$TOOLS_YUI/scripts/Exaptive:$PATH"
	export PATH
}

setupCustomVariables() {
	# Nothing yet
	: 
}

setupTools() {
	## Tools
	# iterm
	source ~/.iterm2_shell_integration.`basename $SHELL`

	# autojump
	[[ -s ~/.autojump/etc/profile.d/autojump.sh ]] && source ~/.autojump/etc/profile.d/autojump.sh

	# z
	[[ -s ~/.z.sh ]] && source ~/.z.sh

	# iTerm
	test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

	# GPG
	SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
	export SSH_AUTH_SOCK
	gpgconf --launch gpg-agent

	# Stubby
	if [[ -d /usr/local/opt/stubby ]]
	then
		# Stubby helpers
		stubby_setdns() {
			# shellcheck disable=SC2068
			sudo bash /usr/local/opt/stubby/sbin/stubby-setdns-macos.sh $@
		}
		stubby_log() {
			# shellcheck disable=SC2068
			sudo less $@ /usr/local/var/log/stubby/stubby.log
		}
		stubby_server_key() {
			local host
			local port
			host=$1
			port=${2:-853}
			certificate=$(echo "" | openssl s_client -connect "${host}:${port}" 2>/dev/null)
			if [[ ! "$certificate" ]]; then echo "No certificate for ${host}:${port}"; return; fi
			echo "$certificate" |
			   openssl x509 -pubkey -noout |
			   openssl pkey -pubin -outform der |
			   openssl dgst -sha256 -binary |
			   openssl enc -base64
		}
	fi

	GPG_TTY=$(tty)
	export GPG_TTY
}

main
