#!/bin/bash
NEO4JHOST="db-jflvtz87sborvx6wea36.graphenedb.com"
LOCAL_HTTPPORT=13334
NEO4J_HTTPPORT=24780
LOCAL_BOLTPORT=13335
NEO4J_BOLTPORT=24786

cat <<END
Tunneling to
http $NEO4JHOST:$NEO4J_HTTPPORT at localhost:$LOCAL_HTTPPORT
bolt $NEO4JHOST:$NEO4J_BOLTPORT at localhost:$LOCAL_BOLTPORT
END
echo "Tunnelling http to $NEO4JHOST:$NEO4J_HTTPPORT at localhost:$LOCAL_HTTPPORT"
ssh -N \
	-L "$LOCAL_HTTPPORT:$NEO4JHOST:$NEO4J_HTTPPORT" \
	-L "$LOCAL_BOLTPORT:$NEO4JHOST:$NEO4J_BOLTPORT" \
	yui@cognitive.exaptive.city

